/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package contact.insertModule.domainLayer.businessObjects;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGJL4/gqkebrXY= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGJL4/gqkebrXY= >>
// ----------- >>
public class Résultat {
    // ----------- << attribute.annotations@AAAAAAGJL4/gqkegcg8= >>
    // ----------- >>
    private int numResultat;

    // ----------- << attribute.annotations@AAAAAAGJL4/gqkeh27A= >>
    // ----------- >>
    private Medaille medaille;

    private int getNumResultat() {
        return numResultat;
    }

    private Medaille getMedaille() {
        return medaille;
    }

    private void setNumResultat(int numResultat) {
        this.numResultat = numResultat;
    }

    private void setMedaille(Medaille medaille) {
        this.medaille = medaille;
    }

    /**
    * @param valeur
    */

    // ----------- << method.annotations@AAAAAAGJL4/gqkeiVnI= >>
    // ----------- >>
    public void setNumResultat(int valeur) {
    // ----------- << method.body@AAAAAAGJL4/gqkeiVnI= >>
    // ----------- >>
    }
    /**
    * @param résultat
    */

    // ----------- << method.annotations@AAAAAAGJL4/gqkekdpI= >>
    // ----------- >>
    public int GetNumResultat(Résultat résultat) {
    // ----------- << method.body@AAAAAAGJL4/gqkekdpI= >>
    // ----------- >>
    }
    /**
    * @param medaille
    */

    // ----------- << method.annotations@AAAAAAGJL4/gqken+Io= >>
    // ----------- >>
    public void SetMedaille(void medaille) {
    // ----------- << method.body@AAAAAAGJL4/gqken+Io= >>
    // ----------- >>
    }
    /**
    * @param resultat
    */

    // ----------- << method.annotations@AAAAAAGJL4/gqkepVHU= >>
    // ----------- >>
    public Medaille GetMedaille(Résultat resultat) {
    // ----------- << method.body@AAAAAAGJL4/gqkepVHU= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGJL4/gqkebrXY= >>
// ----------- >>
}