/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package ogrod.insertModule.domainLayer.businessLogic;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGJL4/gq0e1DXQ= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGJL4/gq0e1DXQ= >>
// ----------- >>
public class InsertionAthlete implements I_InsertionAthlete {
    // ----------- << method.annotations@AAAAAAGJL4/gq0e4jeg= >>
    // ----------- >>
    public static void main() {
    // ----------- << method.body@AAAAAAGJL4/gq0e4jeg= >>
    // ----------- >>
    }
    /**
    * @param csv_file_path
    */

    // ----------- << method.annotations@AAAAAAGJNsWzlBgihFU= >>
    // ----------- >>
    public static void athleteRechargementInDb(String csv_file_path) {
    // ----------- << method.body@AAAAAAGJNsWzlBgihFU= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGJL4/gq0e1DXQ= >>
// ----------- >>
}