/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package contact.insertModule.domainLayer.businessLogic;

import java.util.*;
import java.time.*;


import contact.insertModule.domainLayer.businessObjects.Athlete;
import contact.insertModule.persistenceLayer.AthleteDAO;
// ----------- << imports@AAAAAAGJL4/gq0e5AMY= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGJL4/gq0e5AMY= >>
// ----------- >>
public class AthleteService {
    // ----------- << attribute.annotations@AAAAAAGJL4/gq0e86Do= >>
    // ----------- >>
    private static AthleteService singleton;

    // ----------- << attribute.annotations@AAAAAAGJMDrIJBZEDKs= >>
    // ----------- >>
    private AthleteDAO athleteDAO;

    // ----------- << attribute.annotations@AAAAAAGJMHKmNlnm9HE= >>
    // ----------- >>
    private Athlete athlete;

    public AthleteDAO getAthleteDAO() {
        return athleteDAO;
    }

    public Athlete getAthlete() {
        return athlete;
    }

    public void setAthleteDAO(AthleteDAO athleteDAO) {
        this.athleteDAO = athleteDAO;
    }

    public void setAthlete(Athlete athlete) {
        this.athlete = athlete;
    }

    // ----------- << method.annotations@AAAAAAGJL4/gq0e9jR8= >>
    // ----------- >>
    private AthleteService() {
    // ----------- << method.body@AAAAAAGJL4/gq0e9jR8= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGJL4/gq0e+agU= >>
    // ----------- >>
    public static AthleteService getSingleton() {
    // ----------- << method.body@AAAAAAGJL4/gq0e+agU= >>
    // ----------- >>
    }
    /**
    * @param entityManager 
    * @param Athlete
    */

    // ----------- << method.annotations@AAAAAAGJL4/gq0fActA= >>
    // ----------- >>
    public void athlele_insert(EntityManager entityManager, Athlete Athlete) {
    // ----------- << method.body@AAAAAAGJL4/gq0fActA= >>
    // ----------- >>
    }
    /**
    * @param openedEntityManager 
    * @param athlete
    */

    // ----------- << method.annotations@AAAAAAGJL4/gq0fCCLQ= >>
    // ----------- >>
    public Athlete athlete_find(EntityManager openedEntityManager, Athlete athlete) {
    // ----------- << method.body@AAAAAAGJL4/gq0fCCLQ= >>
    // ----------- >>
    }
    /**
    * @param Athlete
    */

    // ----------- << method.annotations@AAAAAAGJL4/gq0fETAk= >>
    // ----------- >>
    public Athlete athlete_update(Athlete Athlete) {
    // ----------- << method.body@AAAAAAGJL4/gq0fETAk= >>
    // ----------- >>
    }
    /**
    * @param Athlete
    */

    // ----------- << method.annotations@AAAAAAGJL4/gq0fGmxo= >>
    // ----------- >>
    public void athlete_delete(Athlete Athlete) {
    // ----------- << method.body@AAAAAAGJL4/gq0fGmxo= >>
    // ----------- >>
    }
    /**
    * @param pathCsvFile
    */

    // ----------- << method.annotations@AAAAAAGJL4/gq0fIdgs= >>
    // ----------- >>
    public List<<Athlete>> getAthlete(String pathCsvFile) {
    // ----------- << method.body@AAAAAAGJL4/gq0fIdgs= >>
    // ----------- >>
    }
    /**
    * @param name
    */

    // ----------- << method.annotations@AAAAAAGJMJ8wj4ZWJ5s= >>
    // ----------- >>
    public boolean athlete_checkIfExists(int name) {
    // ----------- << method.body@AAAAAAGJMJ8wj4ZWJ5s= >>
    // ----------- >>
    }
    /**
    * @param listeToClean 
    * @param NumColumnReference
    */

    // ----------- << method.annotations@AAAAAAGJNaliNmfJ5ak= >>
    // ----------- >>
    public  Map<String, Athlete> prepareItemsForInsert(ArrayList<String[]> listeToClean, int NumColumnReference) {
    // ----------- << method.body@AAAAAAGJNaliNmfJ5ak= >>
    // ----------- >>
    }
    /**
    * @param entityManager 
    * @param MapAthletes
    */

    // ----------- << method.annotations@AAAAAAGJNkqFMZlDkss= >>
    // ----------- >>
    public void insertAthletesInDb(EntityManager entityManager, Map<String, Athlete> MapAthletes) {
    // ----------- << method.body@AAAAAAGJNkqFMZlDkss= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGJL4/gq0e5AMY= >>
// ----------- >>
}