/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package contact.insertModule.persistenceLayer;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGJL4/gq0fNmjc= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGJL4/gq0fNmjc= >>
// ----------- >>
public class AthleteDAO<type [object Object]> extends DAO {
    /**
    * @param obj_in
    */

    @Override
    // ----------- << method.annotations@AAAAAAGJL4/gq0fTb5Q= >>
    // ----------- >>
    public T create(T obj_in) {
    // ----------- << method.body@AAAAAAGJL4/gq0fTb5Q= >>
    // ----------- >>
    }
    /**
    * @param nameAthlete
    */

    @Override
    // ----------- << method.annotations@AAAAAAGJL4/gq0fW4aI= >>
    // ----------- >>
    public T find(String nameAthlete) {
    // ----------- << method.body@AAAAAAGJL4/gq0fW4aI= >>
    // ----------- >>
    }
    /**
    * @param obj_in
    */

    @Override
    // ----------- << method.annotations@AAAAAAGJL4/gq0fZJ7k= >>
    // ----------- >>
    public T update(T obj_in) {
    // ----------- << method.body@AAAAAAGJL4/gq0fZJ7k= >>
    // ----------- >>
    }
    /**
    * @param obj
    */

    @Override
    // ----------- << method.annotations@AAAAAAGJL4/gq0fcvGM= >>
    // ----------- >>
    public void delete(T obj) {
    // ----------- << method.body@AAAAAAGJL4/gq0fcvGM= >>
    // ----------- >>
    }
    /**
    * @param nameAthlete
    */

    @Override
    // ----------- << method.annotations@AAAAAAGJL4/grEfe9xQ= >>
    // ----------- >>
    public boolean checkIfExist(String nameAthlete) {
    // ----------- << method.body@AAAAAAGJL4/grEfe9xQ= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGJMCryVggwiDU= >>
    // ----------- >>
    public AthleteDAO AthleteDAO() {
    // ----------- << method.body@AAAAAAGJMCryVggwiDU= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGJL4/gq0fNmjc= >>
// ----------- >>
}