/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package ogrod.insertModule.domainLayer.businessObjects;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGJL4/gqUdfKuQ= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGJL4/gqUdfKuQ= >>
// ----------- >>
public class Annee_bissextile {
    // ----------- << attribute.annotations@AAAAAAGJL4/gqUdj0II= >>
    // ----------- >>
    private void numAnnee;

    // ----------- << attribute.annotations@AAAAAAGJL4/gqUdkwXM= >>
    // ----------- >>
    private int value;

    // ----------- << attribute.annotations@AAAAAAGJL4/gqUdiCuA= >>
    // ----------- >>
    private Session comporte;

    private void getNumAnnee() {
        return numAnnee;
    }

    private int getValue() {
        return value;
    }

    public Session getComporte() {
        return comporte;
    }

    private void setNumAnnee(void numAnnee) {
        this.numAnnee = numAnnee;
    }

    private void setValue(int value) {
        this.value = value;
    }

    public void setComporte(Session comporte) {
        this.comporte = comporte;
    }

    public void linkComporte(Session _comporte) {
        if (_comporte != null) {
            _comporte.unlinkEst_associée();
            _comporte.setEst_associée(this);
        }

        unlinkComporte();
        setComporte(_comporte);
    }

    public void unlinkComporte() {
        if (getComporte() != null) {
            getComporte().setEst_associée(null);
            setComporte(null);
        }
    }

    /**
    * @param value
    */

    // ----------- << method.annotations@AAAAAAGJL4/gqUdlg98= >>
    // ----------- >>
    public void setNumAnnee(int value) {
    // ----------- << method.body@AAAAAAGJL4/gqUdlg98= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGJL4/gqUdntaE= >>
    // ----------- >>
    public int getNumAnnee() {
    // ----------- << method.body@AAAAAAGJL4/gqUdntaE= >>
    // ----------- >>
    }
    /**
    * @param annee
    */

    // ----------- << method.annotations@AAAAAAGJL4/gqUdpxt4= >>
    // ----------- >>
    public void setValue(int annee) {
    // ----------- << method.body@AAAAAAGJL4/gqUdpxt4= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGJL4/gqUdrhCI= >>
    // ----------- >>
    public int getValue() {
    // ----------- << method.body@AAAAAAGJL4/gqUdrhCI= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGJL4/gqUdfKuQ= >>
// ----------- >>
}