/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package ogrod.insertModule.domainLayer.businessObjects;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGJL4/gqUdtN4U= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGJL4/gqUdtN4U= >>
// ----------- >>
public class Athlete {
    // ----------- << attribute.annotations@AAAAAAGJL4/gqUdxzsU= >>
    // ----------- >>
    private int numAthlete;

    // ----------- << attribute.annotations@AAAAAAGJL4/gqUdyvgs= >>
    // ----------- >>
    private Genre sexe;

    // ----------- << attribute.annotations@AAAAAAGJL4/gqUdzcZI= >>
    // ----------- >>
    private String nom;

    // ----------- << attribute.annotations@AAAAAAGJL4/gqUd0T1o= >>
    // ----------- >>
    private int age;

    // ----------- << attribute.annotations@AAAAAAGJL4/gqUd1hB4= >>
    // ----------- >>
    private int poids;

    // ----------- << attribute.annotations@AAAAAAGJL4/gqUd2KH4= >>
    // ----------- >>
    private int taille;

    // ----------- << attribute.annotations@AAAAAAGJL4/gqkeemwM= >>
    // ----------- >>
    private Set<Epreuve> réalise = new HashSet<>();

    // ----------- << attribute.annotations@AAAAAAGJL4/gqUdw2iQ= >>
    // ----------- >>
    private Set<Equipe> concourt dans = new HashSet<>();

    private int getNumAthlete() {
        return numAthlete;
    }

    private Genre getSexe() {
        return sexe;
    }

    private String getNom() {
        return nom;
    }

    private int getAge() {
        return age;
    }

    private int getPoids() {
        return poids;
    }

    private int getTaille() {
        return taille;
    }

    public Set<Epreuve> getRéalise() {
        return réalise;
    }

    public Set<Equipe> getConcourt dans() {
        return concourt dans;
    }

    private void setNumAthlete(int numAthlete) {
        this.numAthlete = numAthlete;
    }

    private void setSexe(Genre sexe) {
        this.sexe = sexe;
    }

    private void setNom(String nom) {
        this.nom = nom;
    }

    private void setAge(int age) {
        this.age = age;
    }

    private void setPoids(int poids) {
        this.poids = poids;
    }

    private void setTaille(int taille) {
        this.taille = taille;
    }

    public void linkRéalise(Epreuve _réalise) {
        if (_réalise != null) {
    		_réalise.getEst réalisée().add(this);
            getRéalise().add(_réalise);
        }
    }

    public void linkConcourt dans(Equipe _concourt dans) {
        if (_concourt dans != null) {
    		_concourt dans.getEst composée().add(this);
            getConcourt dans().add(_concourt dans);
        }
    }

    public void unlinkRéalise(Epreuve _réalise) {
        if (_réalise != null) {
            _réalise.getEst réalisée().remove(this);
            getRéalise().remove(_réalise);
        }
    };

    public void unlinkRéalise(Epreuve _réalise, Iterator<Epreuve> it) {
        if (_réalise != null) {
            _réalise.getEst réalisée().remove(this);
            it.remove();
        }
    }

    public void unlinkConcourt dans(Equipe _concourt dans) {
        if (_concourt dans != null) {
            _concourt dans.getEst composée().remove(this);
            getConcourt dans().remove(_concourt dans);
        }
    };

    public void unlinkConcourt dans(Equipe _concourt dans, Iterator<Equipe> it) {
        if (_concourt dans != null) {
            _concourt dans.getEst composée().remove(this);
            it.remove();
        }
    }

    /**
    * @param name
    */

    // ----------- << method.annotations@AAAAAAGJL4/gqUd32EY= >>
    // ----------- >>
    public Athlete Athlete(String name) {
    // ----------- << method.body@AAAAAAGJL4/gqUd32EY= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGJL4/gqUd506U= >>
    // ----------- >>
    public int getNumAthlete() {
    // ----------- << method.body@AAAAAAGJL4/gqUd506U= >>
    // ----------- >>
    }
    /**
    * @param numValue
    */

    // ----------- << method.annotations@AAAAAAGJL4/gqUd7vSM= >>
    // ----------- >>
    public void setNumAthlete(int numValue) {
    // ----------- << method.body@AAAAAAGJL4/gqUd7vSM= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGJL4/gqUd961I= >>
    // ----------- >>
    public Genre getSexe() {
    // ----------- << method.body@AAAAAAGJL4/gqUd961I= >>
    // ----------- >>
    }
    /**
    * @param value
    */

    // ----------- << method.annotations@AAAAAAGJL4/gqUd/OZI= >>
    // ----------- >>
    public void setSexe(Genre value) {
    // ----------- << method.body@AAAAAAGJL4/gqUd/OZI= >>
    // ----------- >>
    }
    /**
    * @param name
    */

    // ----------- << method.annotations@AAAAAAGJL4/gqUeBfYk= >>
    // ----------- >>
    public void setNom(String name) {
    // ----------- << method.body@AAAAAAGJL4/gqUeBfYk= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGJL4/gqUeDZHE= >>
    // ----------- >>
    public String getNom() {
    // ----------- << method.body@AAAAAAGJL4/gqUeDZHE= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGJL4/gqUeFdic= >>
    // ----------- >>
    public int getAge() {
    // ----------- << method.body@AAAAAAGJL4/gqUeFdic= >>
    // ----------- >>
    }
    /**
    * @param age
    */

    // ----------- << method.annotations@AAAAAAGJL4/gqUeHXHY= >>
    // ----------- >>
    public void setAge(int age) {
    // ----------- << method.body@AAAAAAGJL4/gqUeHXHY= >>
    // ----------- >>
    }
    /**
    * @param poids
    */

    // ----------- << method.annotations@AAAAAAGJL4/gqkeJbUw= >>
    // ----------- >>
    public void setPoids(int poids) {
    // ----------- << method.body@AAAAAAGJL4/gqkeJbUw= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGJL4/gqkeLvww= >>
    // ----------- >>
    public int getPoids() {
    // ----------- << method.body@AAAAAAGJL4/gqkeLvww= >>
    // ----------- >>
    }
    /**
    * @param taille
    */

    // ----------- << method.annotations@AAAAAAGJL4/gqkeN45s= >>
    // ----------- >>
    public void setTaille(int taille) {
    // ----------- << method.body@AAAAAAGJL4/gqkeN45s= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGJL4/gqkeP9Cs= >>
    // ----------- >>
    public int getTaille() {
    // ----------- << method.body@AAAAAAGJL4/gqkeP9Cs= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGJL4/gqUdtN4U= >>
// ----------- >>
}