/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package ogrod.insertModule.domainLayer.businessObjects;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGJL4/gqkesQ/k= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGJL4/gqkesQ/k= >>
// ----------- >>
public enum Medaille {
    OR,
    ARGENT,
    BRONZE;

// ----------- << enum.extras@AAAAAAGJL4/gqkesQ/k= >>
// ----------- >>
}