/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package ogrod.insertModule.domainLayer.businessObjects;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGJL4/gp0cnzEs= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGJL4/gp0cnzEs= >>
// ----------- >>
public class Session {
    // ----------- << attribute.annotations@AAAAAAGJL4/gp0co+sY= >>
    // ----------- >>
    private int numSession;

    // ----------- << attribute.annotations@AAAAAAGJL4/gp0cpVF8= >>
    // ----------- >>
    private String officialNameGame;

    // ----------- << attribute.annotations@AAAAAAGJL4/gp0ccq2M= >>
    // ----------- >>
    private Set<Equipe> fait_concourir = new HashSet<>();

    // ----------- << attribute.annotations@AAAAAAGJL4/gqEdArsU= >>
    // ----------- >>
    private Set<Epreuve> organise = new HashSet<>();

    // ----------- << attribute.annotations@AAAAAAGJL4/gqUdh2vA= >>
    // ----------- >>
    private Annee_bissextile est_associée;

    // ----------- << attribute.annotations@AAAAAAGJL4/gqEdTmwk= >>
    // ----------- >>
    private Ville est organisée;

    private int getNumSession() {
        return numSession;
    }

    private String getOfficialNameGame() {
        return officialNameGame;
    }

    public Set<Equipe> getFait_concourir() {
        return fait_concourir;
    }

    public Set<Epreuve> getOrganise() {
        return organise;
    }

    public Annee_bissextile getEst_associée() {
        return est_associée;
    }

    public Ville getEst organisée() {
        return est organisée;
    }

    private void setNumSession(int numSession) {
        this.numSession = numSession;
    }

    private void setOfficialNameGame(String officialNameGame) {
        this.officialNameGame = officialNameGame;
    }

    public void setEst_associée(Annee_bissextile est_associée) {
        this.est_associée = est_associée;
    }

    public void setEst organisée(Ville est organisée) {
        this.est organisée = est organisée;
    }

    public void linkFait_concourir(Equipe _fait_concourir) {
        if (_fait_concourir != null) {
    		_fait_concourir.getParticipe().add(this);
            getFait_concourir().add(_fait_concourir);
        }
    }

    public void linkOrganise(Epreuve _organise) {
        if (_organise != null) {
    		_organise.getSe déroule().add(this);
            getOrganise().add(_organise);
        }
    }

    public void linkEst_associée(Annee_bissextile _est_associée) {
        if (_est_associée != null) {
            _est_associée.unlinkComporte();
            _est_associée.setComporte(this);
        }

        unlinkEst_associée();
        setEst_associée(_est_associée);
    }

    public void linkEst organisée(Ville _est organisée) {
        if (_est organisée != null) {
            _est organisée.getOrganise().add(this);
        }

        unlinkEst organisée();
        setEst organisée(_est organisée);
    }

    public void unlinkFait_concourir(Equipe _fait_concourir) {
        if (_fait_concourir != null) {
            _fait_concourir.getParticipe().remove(this);
            getFait_concourir().remove(_fait_concourir);
        }
    };

    public void unlinkFait_concourir(Equipe _fait_concourir, Iterator<Equipe> it) {
        if (_fait_concourir != null) {
            _fait_concourir.getParticipe().remove(this);
            it.remove();
        }
    }

    public void unlinkOrganise(Epreuve _organise) {
        if (_organise != null) {
            _organise.getSe déroule().remove(this);
            getOrganise().remove(_organise);
        }
    };

    public void unlinkOrganise(Epreuve _organise, Iterator<Epreuve> it) {
        if (_organise != null) {
            _organise.getSe déroule().remove(this);
            it.remove();
        }
    }

    public void unlinkEst_associée() {
        if (getEst_associée() != null) {
            getEst_associée().setComporte(null);
            setEst_associée(null);
        }
    }

    public void unlinkEst organisée() {
        if (getEst organisée() != null) {
            getEst organisée().getOrganise().remove(this);
            setEst organisée(null);
        }
    }

    /**
    * @param num
    */

    // ----------- << method.annotations@AAAAAAGJL4/gp0cqey8= >>
    // ----------- >>
    public void setNumSesssion(int num) {
    // ----------- << method.body@AAAAAAGJL4/gp0cqey8= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGJL4/gqEcs/U8= >>
    // ----------- >>
    public int getNumSession() {
    // ----------- << method.body@AAAAAAGJL4/gqEcs/U8= >>
    // ----------- >>
    }
    /**
    * @param Parameter1
    */

    // ----------- << method.annotations@AAAAAAGJL4/gqEcuXWs= >>
    // ----------- >>
    public void setOfficialNameGame(void Parameter1) {
    // ----------- << method.body@AAAAAAGJL4/gqEcuXWs= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGJL4/gqEcwvq0= >>
    // ----------- >>
    public String getOfficialNameGame() {
    // ----------- << method.body@AAAAAAGJL4/gqEcwvq0= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGJL4/gp0cnzEs= >>
// ----------- >>
}