/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package contacts.insertModule.persistenceLayer;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGJL4/grEfhQY0= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGJL4/grEfhQY0= >>
// ----------- >>
public class DAOFactory {
    // ----------- << method.annotations@AAAAAAGJL4/grEfjqdk= >>
    // ----------- >>
    public static AthleteDAO getDAOAthlete() {
    // ----------- << method.body@AAAAAAGJL4/grEfjqdk= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGJL4/grEfhQY0= >>
// ----------- >>
}