/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package codeSourceGeneré.fr.diginamic.Ogrod.OGROD.insertModule.persistenceLayer;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGJL4/gq0fR9Vo= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGJL4/gq0fR9Vo= >>
// ----------- >>
public abstract class DAO<genericType T> {
    /**
    * @param obj_in
    */

    // ----------- << method.annotations@AAAAAAGJL4/gq0fTb5Q= >>
    // ----------- >>
    public abstract T create(T obj_in);
    /**
    * @param nameAthlete
    */

    // ----------- << method.annotations@AAAAAAGJL4/gq0fW4aI= >>
    // ----------- >>
    public abstract T find(String nameAthlete);
    /**
    * @param obj_in
    */

    // ----------- << method.annotations@AAAAAAGJL4/gq0fZJ7k= >>
    // ----------- >>
    public abstract T update(T obj_in);
    /**
    * @param obj
    */

    // ----------- << method.annotations@AAAAAAGJL4/gq0fcvGM= >>
    // ----------- >>
    public abstract void delete(T obj);
    /**
    * @param nameAthlete
    */

    // ----------- << method.annotations@AAAAAAGJL4/grEfe9xQ= >>
    // ----------- >>
    public abstract boolean checkIfExist(String nameAthlete);
// ----------- << class.extras@AAAAAAGJL4/gq0fR9Vo= >>
// ----------- >>
}