/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package contact.insertModule;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGJL+YpfgDzllg= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGJL+YpfgDzllg= >>
// ----------- >>
public interface I_InsertModule {
// ----------- << interface.extras@AAAAAAGJL+YpfgDzllg= >>
// ----------- >>
}