/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package contacts.insertModule.domainLayer.businessObjects;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGJL4/gp0ca/tg= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGJL4/gp0ca/tg= >>
// ----------- >>
public class Equipe {
    // ----------- << attribute.annotations@AAAAAAGJL4/gp0chQUg= >>
    // ----------- >>
    private void numEquipe;

    // ----------- << attribute.annotations@AAAAAAGJL4/gp0cifks= >>
    // ----------- >>
    private String nom;

    // ----------- << attribute.annotations@AAAAAAGJL4/gp0cd0TE= >>
    // ----------- >>
    private Set<Session> participe = new HashSet<>();

    // ----------- << attribute.annotations@AAAAAAGJL4/gp0cgxrM= >>
    // ----------- >>
    private Pays appartient;

    // ----------- << attribute.annotations@AAAAAAGJL4/gqUdvXRk= >>
    // ----------- >>
    private Set<Athlete> est composée = new HashSet<>();

    private void getNumEquipe() {
        return numEquipe;
    }

    private String getNom() {
        return nom;
    }

    public Set<Session> getParticipe() {
        return participe;
    }

    public Pays getAppartient() {
        return appartient;
    }

    public Set<Athlete> getEst composée() {
        return est composée;
    }

    private void setNumEquipe(void numEquipe) {
        this.numEquipe = numEquipe;
    }

    private void setNom(String nom) {
        this.nom = nom;
    }

    public void setAppartient(Pays appartient) {
        this.appartient = appartient;
    }

    public void linkParticipe(Session _participe) {
        if (_participe != null) {
    		_participe.getFait_concourir().add(this);
            getParticipe().add(_participe);
        }
    }

    public void linkAppartient(Pays _appartient) {
        if (_appartient != null) {
            _appartient.getEst associé().add(this);
        }

        unlinkAppartient();
        setAppartient(_appartient);
    }

    public void linkEst composée(Athlete _est composée) {
        if (_est composée != null) {
    		_est composée.getConcourt dans().add(this);
            getEst composée().add(_est composée);
        }
    }

    public void unlinkParticipe(Session _participe) {
        if (_participe != null) {
            _participe.getFait_concourir().remove(this);
            getParticipe().remove(_participe);
        }
    };

    public void unlinkParticipe(Session _participe, Iterator<Session> it) {
        if (_participe != null) {
            _participe.getFait_concourir().remove(this);
            it.remove();
        }
    }

    public void unlinkAppartient() {
        if (getAppartient() != null) {
            getAppartient().getEst associé().remove(this);
            setAppartient(null);
        }
    }

    public void unlinkEst composée(Athlete _est composée) {
        if (_est composée != null) {
            _est composée.getConcourt dans().remove(this);
            getEst composée().remove(_est composée);
        }
    };

    public void unlinkEst composée(Athlete _est composée, Iterator<Athlete> it) {
        if (_est composée != null) {
            _est composée.getConcourt dans().remove(this);
            it.remove();
        }
    }

    /**
    * @param value
    */

    // ----------- << method.annotations@AAAAAAGJL4/gp0cjOTg= >>
    // ----------- >>
    public void setNumEquipe(int value) {
    // ----------- << method.body@AAAAAAGJL4/gp0cjOTg= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGJL4/gp0cl0Hk= >>
    // ----------- >>
    public int getNumEquipe() {
    // ----------- << method.body@AAAAAAGJL4/gp0cl0Hk= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGJL4/gp0ca/tg= >>
// ----------- >>
}