/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package contacts.insertModule.domainLayer.businessObjects;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGJL4/gqkewI/A= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGJL4/gqkewI/A= >>
// ----------- >>
public enum Genre {
    HOMME,
    FEMME,
    NON_GENRE;

// ----------- << enum.extras@AAAAAAGJL4/gqkewI/A= >>
// ----------- >>
}