/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package contacts.insertModule.domainLayer.businessObjects;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGJL4/gqEdRuF8= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGJL4/gqEdRuF8= >>
// ----------- >>
private class Ville {
    // ----------- << attribute.annotations@AAAAAAGJL4/gqEdVrB8= >>
    // ----------- >>
    private void numVille;

    // ----------- << attribute.annotations@AAAAAAGJL4/gqUdWUow= >>
    // ----------- >>
    private String nom;

    // ----------- << attribute.annotations@AAAAAAGJL6021VMPi30= >>
    // ----------- >>
    private Pays est_situee;

    // ----------- << attribute.annotations@AAAAAAGJL4/gqEdUShg= >>
    // ----------- >>
    private Set<Session> organise = new HashSet<>();

    private void getNumVille() {
        return numVille;
    }

    private String getNom() {
        return nom;
    }

    public Pays getEst_situee() {
        return est_situee;
    }

    public Set<Session> getOrganise() {
        return organise;
    }

    private void setNumVille(void numVille) {
        this.numVille = numVille;
    }

    private void setNom(String nom) {
        this.nom = nom;
    }

    public void setEst_situee(Pays est_situee) {
        this.est_situee = est_situee;
    }

    public void linkEst_situee(Pays _est_situee) {
        if (_est_situee != null) {
            _est_situee.getEst_compose().add(this);
        }

        unlinkEst_situee();
        setEst_situee(_est_situee);
    }

    public void linkOrganise(Session _organise) {
        if (_organise != null) {
            _organise.unlinkEst organisée();
            _organise.setEst organisée(this);
            getOrganise().add(_organise);
        }
    }

    public void unlinkEst_situee() {
        if (getEst_situee() != null) {
            getEst_situee().getEst_compose().remove(this);
            setEst_situee(null);
        }
    }

    public void unlinkOrganise(Session _organise) {
        if (_organise != null) {
            _organise.setEst organisée(null);
            getOrganise().remove(_organise);
        }
    }

    public void unlinkOrganise(Session _organise, Iterator<Session> it) {
        if (_organise != null) {
            _organise.setEst organisée(null);
            it.remove();
        }
    }

    /**
    * @param value
    */

    // ----------- << method.annotations@AAAAAAGJL4/gqUdX3FQ= >>
    // ----------- >>
    public void setNumVille(int value) {
    // ----------- << method.body@AAAAAAGJL4/gqUdX3FQ= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGJL4/gqUdZ50s= >>
    // ----------- >>
    public int getNumVille() {
    // ----------- << method.body@AAAAAAGJL4/gqUdZ50s= >>
    // ----------- >>
    }
    /**
    * @param value
    */

    // ----------- << method.annotations@AAAAAAGJL4/gqUdbTn4= >>
    // ----------- >>
    public void setNom(int value) {
    // ----------- << method.body@AAAAAAGJL4/gqUdbTn4= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGJL4/gqUddnZM= >>
    // ----------- >>
    public String getNom() {
    // ----------- << method.body@AAAAAAGJL4/gqUddnZM= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGJL4/gqEdRuF8= >>
// ----------- >>
}