/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package codeSourceGeneré.fr.diginamic.Ogrod.OGROD.insertModule.domainLayer.businessLogic;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGJL4/gq0fLR5M= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGJL4/gq0fLR5M= >>
// ----------- >>
public interface I_InsertionAthlete {
// ----------- << interface.extras@AAAAAAGJL4/gq0fLR5M= >>
// ----------- >>
}